### ISSUE TITLE
Not Working with Ti SDK 8.0.0

### ISSUE THREAD

**Issue by SquirrelMobile** [appcelerator-modules/ti.compression#21]
I've try to use this module with SDK 8.0.0 and there is a problem during the compilation : 

```
[TRACE] Undefined symbols for architecture x86_64:
[TRACE]   "_deflate", referenced from:
[TRACE]       _zipWriteInFileInZip in libti.compression.a(zip.o)
[TRACE]       _zipCloseFileInZipRaw in libti.compression.a(zip.o)
[TRACE]   "_deflateInit2_", referenced from:
[TRACE]       _zipOpenNewFileInZip3 in libti.compression.a(zip.o)
[TRACE]   "_inflate", referenced from:
[TRACE]       _unzReadCurrentFile in libti.compression.a(unzip.o)
[TRACE]   "_get_crc_table", referenced from:
[TRACE]       _unzOpenCurrentFile3 in libti.compression.a(unzip.o)
[TRACE]       _zipOpenNewFileInZip3 in libti.compression.a(zip.o)
[TRACE]   "_deflateEnd", referenced from:
[TRACE]       _zipCloseFileInZipRaw in libti.compression.a(zip.o)
[TRACE]   "_inflateInit2_", referenced from:
[TRACE]       _unzOpenCurrentFile3 in libti.compression.a(unzip.o)
[TRACE]   "_inflateEnd", referenced from:
[TRACE]       _unzCloseCurrentFile in libti.compression.a(unzip.o)
[TRACE]   "_crc32", referenced from:
[TRACE]       -[TiCompressionZipArchive addFileToZip:newname:] in libti.compression.a(ZipArchive.o)
[TRACE]       _unzReadCurrentFile in libti.compression.a(unzip.o)
[TRACE]       _zipWriteInFileInZip in libti.compression.a(zip.o)
[TRACE] ld: symbol(s) not found for architecture x86_64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/buje/Documents/Appcelerator/o-m/build/iphone/build/Products/Debug-iphonesimulator/Orange\ et\ Moi\ Réunion\ Mayotte.app/Orange\ et\ Moi\ Réunion\ Mayotte normal x86_64
[ERROR] (1 failure)
```

**Comment by janvennemann** [comment]
@SquirrelMobile please check the new 2.0.0 release for iOS which should work with the latest SDKs.

**Comment by SquirrelMobile** [comment]
@janvennemann Already tested with the @hansemannn 2.0.0 i've the same problem

**Comment by janvennemann** [comment]
Ok, I just tested with Hans' zip too and I think something is wrong with the file Hans posted. Please check the official release zip from here: https://github.com/appcelerator-modules/ti.compression/releases/tag/ios-2.0.0. This one is working fine.

**Comment by rlustemberg** [comment]
I have a similar issue with ti.crashlytics. I'll file an issue there. Could you explain what the issue here was?
Thanks!

**Comment by janvennemann** [comment]
@rlustemberg i didn't change anything here, just did a rebuild. The old build was probably done on an outdated code base by accident. See my comment in https://github.com/hansemannn/titanium-crashlytics/issues/12 what's is probably causing the error in ti.crashlytics.

**Comment by hbugdoll** [comment]
In my opinion this issue can be closed.
Ti 8 and module version prior to 2.0.0 (module version 1.1.1 is from 2014) are quite outdated.
